-- Simple staff seed — no branch assignment, just role.
-- Run this AFTER branches are seeded or independently.
-- Each staff has a code, name, and role. Assign branches via the app later.

INSERT INTO public.staff (staff_code, full_name, role, active)
SELECT * FROM (VALUES
  ('EMP0021', 'MAGDI IBRAHIM ELTOHAMI MOHAMED BADI', 'Salesperson', true),
  ('EMP0029', 'MELANI BELTRAN LISING', 'Salesperson', true),
  ('EMP0167', 'FIAZ AKHTAR QASMI', 'Pharmacist', true),
  ('EMP0191', 'MOHAMED ABOUELOYON SALAH MOHAMED AYOUB', 'Salesperson', true),
  ('EMP0222', 'LUBNA TABASUM', 'Branch Manager', true),
  ('EMP0359', 'ALI MUKTHAR ABDUL SALEEM', 'Pharmacist', true),
  ('EMP0375', 'HOSSAM MOHAMED KAMEL AHMED', 'Salesperson', true),
  ('EMP0387', 'MALEK AHMED OMAR AHMED DARWISH', 'Salesperson', true),
  ('EMP0424', 'HARLENE PATAYAN', 'Pharmacist', true),
  ('EMP0441', 'JANE DE GUZMAN SOLIMAN', 'Branch Manager', true),
  ('EMP0448', 'WAEL MAHROUS AYOUB AHMED', 'Salesperson', true),
  ('EMP0474', 'JENNIFER GARCIA', 'Salesperson', true),
  ('EMP0500', 'RAMADAN ABOUZEID RAMADAN ALI', 'Pharmacist', true),
  ('EMP0585', 'JOJIT COTELO MENDOZA', 'Salesperson', true),
  ('EMP0611', 'MOHAMED KAMAL ABBAS IBRAHIM LEILA', 'Salesperson', true),
  ('EMP0612', 'KARIM MANSOUR SALEH LISI', 'Salesperson', true),
  ('EMP0618', 'YAHIA MAHMOUD MEGAHED BADWI', 'Salesperson', true),
  ('EMP0622', 'KARIM ABDELLATIF ELSAYED ABDELLATIF', 'Salesperson', true),
  ('EMP0636', 'QURAT UL AIN', 'Pharmacist', true),
  ('EMP0660', 'MOHAMED ADEL ABDELALIM ELHANAFI ELROZY', 'Pharmacist', true),
  ('EMP0677', 'PRINCESS SARAH BAYANI', 'Pharmacist', true),
  ('EMP0678', 'SARAH MOUSTAFA ABDELRAHMAN MOUSTAFA', 'Pharmacist', true),
  ('EMP0692', 'MOHAMED ABDELZAHER NOUR AHMED', 'Salesperson', true),
  ('EMP0693', 'AHMED MOHAMED ATTIA ISMAIL BADAWI', 'Salesperson', true),
  ('EMP0830', 'IMRAN MAHMOOD', 'Salesperson', true),
  ('EMP0864', 'ROSHELLE SUSTENTO', 'Pharmacist', true),
  ('EMP0890', 'SHAMEER NADUVILA VALAPPIL', 'Pharmacist', true),
  ('EMP0896', 'IMRAN KHAN', 'Salesperson', true),
  ('EMP0937', 'RAMY AHMED MOHAMED HAMZAWY HARBY', 'Salesperson', true),
  ('EMP0959', 'DARYLL CABILIN EUGENIO', 'Salesperson', true),
  ('EMP0963', 'TAMER IBRAHIM MABROUK AYOUB', 'Pharmacist', true),
  ('EMP0998', 'MD MAZHARUL ISLAM', 'Branch Manager', true),
  ('EMP1003', 'BILAL MUHAMMAD RIAZ', 'Salesperson', true),
  ('EMP1018', 'KAREEM MOHAMED SALAH GODA ELSAYED', 'Branch Manager', true),
  ('EMP1019', 'GAMAL SAYED ABDELMAWGOUD AHMED', 'Salesperson', true),
  ('EMP1025', 'MOHAMED REDA SABER FATHALLA FATHALLA', 'Salesperson', true),
  ('EMP1050', 'RIZALINA MADAYAG', 'Pharmacist', true),
  ('EMP1062', 'ABDELRAHMAN ELEMAM ABDELHAY SHERA', 'Pharmacist', true),
  ('EMP1083', 'MOHAMED METWALLY ELGERIDY', 'Salesperson', true),
  ('EMP1113', 'ABBAS BANDE HASSAN', 'Pharmacist', true),
  ('EMP1143', 'YOUSRI MOHAMED FATHY GAD', 'Salesperson', true),
  ('EMP1187', 'ALLEN MAE SANDRO', 'Pharmacist', true),
  ('EMP1188', 'ZEESHAN RAZZAQ', 'Pharmacist', true),
  ('EMP1189', 'MOHAMED ELSAYED ELSHESHTAWI ELSEBAEI', 'Salesperson', true),
  ('EMP1229', 'AHMED MAHER MAAMOUN MAHMOUD SALMA', 'Salesperson', true),
  ('EMP1289', 'VIANNE GIA GUMABAO MACUTAY', 'Pharmacist', true),
  ('EMP1290', 'NOSIBA MOHAMED SIDDIG', 'Pharmacist', true),
  ('EMP1292', 'MOHAMED GAMAL ABDELMAGUID ELSADANY', 'Pharmacist', true),
  ('EMP1296', 'MARWA HUSSIN MOHAMED ALASS', 'Pharmacist', true),
  ('EMP1299', 'OLA MOHAMMED ABUZAID ALI', 'Pharmacist', true),
  ('EMP1312', 'GERLIE ROSE FELICIANO SARTE', 'Pharmacist', true),
  ('EMP1316', 'AHMED OTHMAN GHANEM OTHMAN', 'Salesperson', true),
  ('EMP1326', 'REDA MOHAMED ABOELFTOH ELSHERIF', 'Pharmacist', true),
  ('EMP1331', 'JOYCE DELMUNDO', 'Pharmacist', true),
  ('EMP1332', 'MA JOYCE ANN SERRANO', 'Pharmacist', true),
  ('EMP1342', 'ABDELRAHMAN HASSAN FATHY HASSAN', 'Salesperson', true),
  ('EMP1346', 'MOUSTAFA ALI MOHAMED MARAWAN GAD', 'Salesperson', true),
  ('EMP1350', 'MOHAMAD NIDAL BADER ALDEEN ALMOUSLI', 'Pharmacist', true),
  ('EMP1369', 'MOHAMED SABRY ZAKARIA MOHAMED KEWAN', 'Salesperson', true),
  ('EMP1425', 'HAITHAM ALDURRA', 'Branch Manager', true),
  ('EMP1442', 'KHALED MOHAMED MOHAMED ELSAID ABDELAZIZ TAKSIRA', 'Salesperson', true),
  ('EMP1445', 'NEVINE SERAGELDIN HUSSIEN KADRY', 'Pharmacist', true),
  ('EMP1446', 'AHMED MOUSTAFA MOHAMED MOUSTAFA KOTB', 'Pharmacist', true),
  ('EMP1449', 'MAHMOUD ABDULKADER ANIS KARKANAWI', 'Pharmacist', true),
  ('EMP1459', 'OMNIA AHMED ATTIA MOHAMED IBRAHIM', 'Pharmacist', true),
  ('EMP1478', 'SHAYMAA IBRAHIM ABDELMAGED IBRAHIM', 'Salesperson', true),
  ('EMP1482', 'FATMA MAGDY SALAMA ABUSREA', 'Pharmacist', true),
  ('EMP1483', 'RASHIDA ERANHIKKAL', 'Pharmacist', true),
  ('EMP1489', 'ABDELMONEIM ABDELAZIM ABDELMONEIM MAHMOUD SOLIMAN', 'Pharmacist', true),
  ('EMP1490', 'JOAN MAE GARCIA GARCIA', 'Pharmacist', true),
  ('EMP1502', 'FIRDOUS UDDIN AMER MOHAMMED', 'Pharmacist', true),
  ('EMP1520', 'SAEED JASEEM MULLASSERI', 'Pharmacist', true),
  ('EMP1521', 'VANESSA HERMOGENO AGAPITO', 'Pharmacist', true),
  ('EMP1649', 'MOHAMED TAHA ELGABRI IBRAHIM ELHENNAWI', 'Salesperson', true),
  ('EMP1651', 'NOURELHODA ESSMAT MOATAMED SAYED', 'Branch Manager', true),
  ('EMP1652', 'AMR MOHAMED ALAA MOHAMED IBRAHIM ALDOKLA', 'Pharmacist', true),
  ('EMP1657', 'SANJID CHIRAKKAL', 'Pharmacist', true),
  ('EMP1660', 'MOHAMED HASSAN NASR GHANNAM', 'Pharmacist', true),
  ('EMP1662', 'AHMED MOHAMED MAHMOUD MOHAMED', 'Pharmacist', true),
  ('EMP1663', 'REMYLYN DEALAGDON TOLORIO', 'Salesperson', true),
  ('EMP1664', 'MARIEL RIZARO ELMENZO', 'Salesperson', true),
  ('EMP1665', 'ABDELAZIZ FAROUK SHAMESELDIN ELHOGRY', 'Salesperson', true),
  ('EMP1667', 'MOHAMED MONIR ABDELMONEM IBRAHIM GHAZAL', 'Salesperson', true),
  ('EMP1668', 'MOSAB MOHAMMED ABBAS HADDAD', 'Pharmacist', true),
  ('EMP1670', 'HANAN AL DALI', 'Salesperson', true),
  ('EMP1672', 'ESRAA LOTFY SAAD ABDELLATIF MOHARM', 'Pharmacist', true),
  ('EMP1674', 'ESLAM HESHAM ELSAYED MOKHTAR GABALLAH', 'Pharmacist', true),
  ('EMP1676', 'MARWA MOHAMED OMAR MOHAMED', 'Pharmacist', true),
  ('EMP1677', 'RISLA CHITARRAYIL', 'Pharmacist', true),
  ('EMP1679', 'GRACIELLE DE BORJA VITOR', 'Salesperson', true),
  ('EMP1706', 'MOHAMED HAMED ELHUSSEINI ELTANTAWI', 'Pharmacist', true),
  ('EMP1715', 'SURESH NAGARAJAN', 'Pharmacist', true),
  ('EMP1716', 'AHMED MOHAMED TAREK MOHAMED MAMDOUH MAHMOUD', 'Pharmacist', true),
  ('EMP1733', 'MOSTAFA MABROUK SALOUMA MOHAMED', 'Salesperson', true),
  ('EMP1734', 'EMAN AHMED ELSHHAT ELNGAR', 'Salesperson', true),
  ('EMP1740', 'MUHAMMAD ELSAYED BEDEIR MUHAMMAD ELKHOLEY', 'Salesperson', true),
  ('EMP1742', 'ISLAM ABDELMAWLA ELSAYED ABDELMAWLA', 'Pharmacist', true),
  ('EMP1743', 'AHMED SALAH ABDELNABY ELHENNAWI', 'Pharmacist', true),
  ('EMP1744', 'EZZAT ABED ABDELHAMED ABDELWAHAB ABDELHAFEZ', 'Pharmacist', true),
  ('EMP1745', 'HAZEM MOHAMED SAAD ABDELWAHAB', 'Pharmacist', true),
  ('EMP1746', 'SAMI TAHA ABDELAATI TAHA SEWILAM', 'Pharmacist', true),
  ('EMP1749', 'ISLAM ALI WAHDAN AYOUB ELSHERBINI', 'Pharmacist', true),
  ('EMP1750', 'ZIA UR REHMAN', 'Pharmacist', true),
  ('EMP1751', 'ABDUL SAMAD UMER FAROOQ', 'Pharmacist', true),
  ('EMP1753', 'NOURHAN ABDELNASSER ELSAYED ELSHERBINI', 'Pharmacist', true),
  ('EMP1756', 'TAREK SAAD ABDELMOAMEN ALI', 'Pharmacist', true),
  ('EMP1759', 'AHMED KAMAL IBRAHIM ALI SOLIMAN', 'Pharmacist', true),
  ('EMP1766', 'ABANOUB BOULES SABRY DERIAS', 'Pharmacist', true),
  ('EMP1769', 'MOHAMED RAMZY ELKOTB ABDELHAMID', 'Pharmacist', true),
  ('EMP1770', 'JOHN SOLIMAN RAMZY BEKHET FALFAL', 'Pharmacist', true),
  ('EMP1773', 'REFAAT ABDELAZIZ AWAD ELDESOKY', 'Salesperson', true),
  ('EMP1775', 'AHMED ELSAYED AHMED MOHAMED ELGELANY', 'Pharmacist', true),
  ('EMP1776', 'RONALYNN LORENZO MATIC', 'Salesperson', true),
  ('EMP1778', 'HUSSEIN GHANEM MAKAWI ABDELKAWI', 'Salesperson', true),
  ('EMP1794', 'AIRAH EBERLEEN PERICO', 'Salesperson', true),
  ('EMP1803', 'HASAN ELSAID HASAN ABDELAZIZ', 'Salesperson', true),
  ('EMP1806', 'MAHMOUD SOBHI MOHAMED MOHAMED ELDOMYATY', 'Pharmacist', true),
  ('EMP1809', 'JONNALYN PADILLA PEREZ', 'Salesperson', true),
  ('EMP1811', 'AHMED SALAHELDIN AHMED GHALY', 'Pharmacist', true),
  ('EMP1822', 'MOSTAFA MAHMOUD MOHAMED ELSREOGY', 'Salesperson', true),
  ('EMP1840', 'MOHAMMED MOSTAFA MOHAMMED ELSHENNAWY', 'Pharmacist', true),
  ('EMP1841', 'ZENDIE MAE SALARDA VELONERO', 'Salesperson', true),
  ('EMP1850', 'GAMAL ABDELNASER ABDELHAMID AHMED ABDELRAHMAN', 'Pharmacist', true),
  ('EMP1851', 'AHMED MOHAMED SAAD MOHAMED MAHMOUD ELATFY', 'Pharmacist', true),
  ('EMP1863', 'SOHA ABDELHAMID BAYOUMI OKDA', 'Pharmacist', true),
  ('EMP1875', 'SAIF RAIF WASSFY HANNA', 'Pharmacist', true),
  ('EMP1876', 'ABDELRAHMAN MAHMOUD FAWZY MAHMOUD', 'Pharmacist', true),
  ('EMP1879', 'ZUBAIR POTTACHOLA', 'Pharmacist', true),
  ('EMP1880', 'AHMED MOSILHY ABDELALEEM MOSILHY', 'Pharmacist', true),
  ('EMP1890', 'SAIF MOHAMED MOHAMED GAD ELASSAL', 'Pharmacist', true),
  ('EMP1902', 'ALAA MORSY MOHAMMAD BARAKAT', 'Pharmacist', true),
  ('EMP1903', 'SHADI MOHAMED MAHMOUD WAHBA BEHIR', 'Pharmacist', true),
  ('EMP1907', 'ALENOUD MOUSTAFA KAMEL ABDELGHAFAR', 'Salesperson', true),
  ('EMP1914', 'ABDERAHMAN MOSTAFA MOHAMED ELSAYED SOLIMAN', 'Pharmacist', true)
) AS t(staff_code, full_name, role, active)
ON CONFLICT (staff_code) DO NOTHING;
