-- Simple staff seed — no branch assignment, just role.
-- Run this AFTER branches are seeded or independently.
-- Each staff has a code, name, and role. Assign branches via the app later.

INSERT INTO public.staff (staff_code, full_name, role, active)
VALUES
  ('EMP0021', 'MAGDI IBRAHIM ELTOHAMI MOHAMED BADI', 'Salesperson'::public.staff_role, true),
  ('EMP0029', 'MELANI BELTRAN LISING', 'Salesperson'::public.staff_role, true),
  ('EMP0167', 'FIAZ AKHTAR QASMI', 'Pharmacist'::public.staff_role, true),
  ('EMP0191', 'MOHAMED ABOUELOYON SALAH MOHAMED AYOUB', 'Salesperson'::public.staff_role, true),
  ('EMP0222', 'LUBNA TABASUM', 'Branch Manager'::public.staff_role, true),
  ('EMP0359', 'ALI MUKTHAR ABDUL SALEEM', 'Pharmacist'::public.staff_role, true),
  ('EMP0375', 'HOSSAM MOHAMED KAMEL AHMED', 'Salesperson'::public.staff_role, true),
  ('EMP0387', 'MALEK AHMED OMAR AHMED DARWISH', 'Salesperson'::public.staff_role, true),
  ('EMP0424', 'HARLENE PATAYAN', 'Pharmacist'::public.staff_role, true),
  ('EMP0441', 'JANE DE GUZMAN SOLIMAN', 'Branch Manager'::public.staff_role, true),
  ('EMP0448', 'WAEL MAHROUS AYOUB AHMED', 'Salesperson'::public.staff_role, true),
  ('EMP0474', 'JENNIFER GARCIA', 'Salesperson'::public.staff_role, true),
  ('EMP0500', 'RAMADAN ABOUZEID RAMADAN ALI', 'Pharmacist'::public.staff_role, true),
  ('EMP0585', 'JOJIT COTELO MENDOZA', 'Salesperson'::public.staff_role, true),
  ('EMP0611', 'MOHAMED KAMAL ABBAS IBRAHIM LEILA', 'Salesperson'::public.staff_role, true),
  ('EMP0612', 'KARIM MANSOUR SALEH LISI', 'Salesperson'::public.staff_role, true),
  ('EMP0618', 'YAHIA MAHMOUD MEGAHED BADWI', 'Salesperson'::public.staff_role, true),
  ('EMP0622', 'KARIM ABDELLATIF ELSAYED ABDELLATIF', 'Salesperson'::public.staff_role, true),
  ('EMP0636', 'QURAT UL AIN', 'Pharmacist'::public.staff_role, true),
  ('EMP0660', 'MOHAMED ADEL ABDELALIM ELHANAFI ELROZY', 'Pharmacist'::public.staff_role, true),
  ('EMP0677', 'PRINCESS SARAH BAYANI', 'Pharmacist'::public.staff_role, true),
  ('EMP0678', 'SARAH MOUSTAFA ABDELRAHMAN MOUSTAFA', 'Pharmacist'::public.staff_role, true),
  ('EMP0692', 'MOHAMED ABDELZAHER NOUR AHMED', 'Salesperson'::public.staff_role, true),
  ('EMP0693', 'AHMED MOHAMED ATTIA ISMAIL BADAWI', 'Salesperson'::public.staff_role, true),
  ('EMP0830', 'IMRAN MAHMOOD', 'Salesperson'::public.staff_role, true),
  ('EMP0864', 'ROSHELLE SUSTENTO', 'Pharmacist'::public.staff_role, true),
  ('EMP0890', 'SHAMEER NADUVILA VALAPPIL', 'Pharmacist'::public.staff_role, true),
  ('EMP0896', 'IMRAN KHAN', 'Salesperson'::public.staff_role, true),
  ('EMP0937', 'RAMY AHMED MOHAMED HAMZAWY HARBY', 'Salesperson'::public.staff_role, true),
  ('EMP0959', 'DARYLL CABILIN EUGENIO', 'Salesperson'::public.staff_role, true),
  ('EMP0963', 'TAMER IBRAHIM MABROUK AYOUB', 'Pharmacist'::public.staff_role, true),
  ('EMP0998', 'MD MAZHARUL ISLAM', 'Branch Manager'::public.staff_role, true),
  ('EMP1003', 'BILAL MUHAMMAD RIAZ', 'Salesperson'::public.staff_role, true),
  ('EMP1018', 'KAREEM MOHAMED SALAH GODA ELSAYED', 'Branch Manager'::public.staff_role, true),
  ('EMP1019', 'GAMAL SAYED ABDELMAWGOUD AHMED', 'Salesperson'::public.staff_role, true),
  ('EMP1025', 'MOHAMED REDA SABER FATHALLA FATHALLA', 'Salesperson'::public.staff_role, true),
  ('EMP1050', 'RIZALINA MADAYAG', 'Pharmacist'::public.staff_role, true),
  ('EMP1062', 'ABDELRAHMAN ELEMAM ABDELHAY SHERA', 'Pharmacist'::public.staff_role, true),
  ('EMP1083', 'MOHAMED METWALLY ELGERIDY', 'Salesperson'::public.staff_role, true),
  ('EMP1113', 'ABBAS BANDE HASSAN', 'Pharmacist'::public.staff_role, true),
  ('EMP1143', 'YOUSRI MOHAMED FATHY GAD', 'Salesperson'::public.staff_role, true),
  ('EMP1187', 'ALLEN MAE SANDRO', 'Pharmacist'::public.staff_role, true),
  ('EMP1188', 'ZEESHAN RAZZAQ', 'Pharmacist'::public.staff_role, true),
  ('EMP1189', 'MOHAMED ELSAYED ELSHESHTAWI ELSEBAEI', 'Salesperson'::public.staff_role, true),
  ('EMP1229', 'AHMED MAHER MAAMOUN MAHMOUD SALMA', 'Salesperson'::public.staff_role, true),
  ('EMP1289', 'VIANNE GIA GUMABAO MACUTAY', 'Pharmacist'::public.staff_role, true),
  ('EMP1290', 'NOSIBA MOHAMED SIDDIG', 'Pharmacist'::public.staff_role, true),
  ('EMP1292', 'MOHAMED GAMAL ABDELMAGUID ELSADANY', 'Pharmacist'::public.staff_role, true),
  ('EMP1296', 'MARWA HUSSIN MOHAMED ALASS', 'Pharmacist'::public.staff_role, true),
  ('EMP1299', 'OLA MOHAMMED ABUZAID ALI', 'Pharmacist'::public.staff_role, true),
  ('EMP1312', 'GERLIE ROSE FELICIANO SARTE', 'Pharmacist'::public.staff_role, true),
  ('EMP1316', 'AHMED OTHMAN GHANEM OTHMAN', 'Salesperson'::public.staff_role, true),
  ('EMP1326', 'REDA MOHAMED ABOELFTOH ELSHERIF', 'Pharmacist'::public.staff_role, true),
  ('EMP1331', 'JOYCE DELMUNDO', 'Pharmacist'::public.staff_role, true),
  ('EMP1332', 'MA JOYCE ANN SERRANO', 'Pharmacist'::public.staff_role, true),
  ('EMP1342', 'ABDELRAHMAN HASSAN FATHY HASSAN', 'Salesperson'::public.staff_role, true),
  ('EMP1346', 'MOUSTAFA ALI MOHAMED MARAWAN GAD', 'Salesperson'::public.staff_role, true),
  ('EMP1350', 'MOHAMAD NIDAL BADER ALDEEN ALMOUSLI', 'Pharmacist'::public.staff_role, true),
  ('EMP1369', 'MOHAMED SABRY ZAKARIA MOHAMED KEWAN', 'Salesperson'::public.staff_role, true),
  ('EMP1425', 'HAITHAM ALDURRA', 'Branch Manager'::public.staff_role, true),
  ('EMP1442', 'KHALED MOHAMED MOHAMED ELSAID ABDELAZIZ TAKSIRA', 'Salesperson'::public.staff_role, true),
  ('EMP1445', 'NEVINE SERAGELDIN HUSSIEN KADRY', 'Pharmacist'::public.staff_role, true),
  ('EMP1446', 'AHMED MOUSTAFA MOHAMED MOUSTAFA KOTB', 'Pharmacist'::public.staff_role, true),
  ('EMP1449', 'MAHMOUD ABDULKADER ANIS KARKANAWI', 'Pharmacist'::public.staff_role, true),
  ('EMP1459', 'OMNIA AHMED ATTIA MOHAMED IBRAHIM', 'Pharmacist'::public.staff_role, true),
  ('EMP1478', 'SHAYMAA IBRAHIM ABDELMAGED IBRAHIM', 'Salesperson'::public.staff_role, true),
  ('EMP1482', 'FATMA MAGDY SALAMA ABUSREA', 'Pharmacist'::public.staff_role, true),
  ('EMP1483', 'RASHIDA ERANHIKKAL', 'Pharmacist'::public.staff_role, true),
  ('EMP1489', 'ABDELMONEIM ABDELAZIM ABDELMONEIM MAHMOUD SOLIMAN', 'Pharmacist'::public.staff_role, true),
  ('EMP1490', 'JOAN MAE GARCIA GARCIA', 'Pharmacist'::public.staff_role, true),
  ('EMP1502', 'FIRDOUS UDDIN AMER MOHAMMED', 'Pharmacist'::public.staff_role, true),
  ('EMP1520', 'SAEED JASEEM MULLASSERI', 'Pharmacist'::public.staff_role, true),
  ('EMP1521', 'VANESSA HERMOGENO AGAPITO', 'Pharmacist'::public.staff_role, true),
  ('EMP1649', 'MOHAMED TAHA ELGABRI IBRAHIM ELHENNAWI', 'Salesperson'::public.staff_role, true),
  ('EMP1651', 'NOURELHODA ESSMAT MOATAMED SAYED', 'Branch Manager'::public.staff_role, true),
  ('EMP1652', 'AMR MOHAMED ALAA MOHAMED IBRAHIM ALDOKLA', 'Pharmacist'::public.staff_role, true),
  ('EMP1657', 'SANJID CHIRAKKAL', 'Pharmacist'::public.staff_role, true),
  ('EMP1660', 'MOHAMED HASSAN NASR GHANNAM', 'Pharmacist'::public.staff_role, true),
  ('EMP1662', 'AHMED MOHAMED MAHMOUD MOHAMED', 'Pharmacist'::public.staff_role, true),
  ('EMP1663', 'REMYLYN DEALAGDON TOLORIO', 'Salesperson'::public.staff_role, true),
  ('EMP1664', 'MARIEL RIZARO ELMENZO', 'Salesperson'::public.staff_role, true),
  ('EMP1665', 'ABDELAZIZ FAROUK SHAMESELDIN ELHOGRY', 'Salesperson'::public.staff_role, true),
  ('EMP1667', 'MOHAMED MONIR ABDELMONEM IBRAHIM GHAZAL', 'Salesperson'::public.staff_role, true),
  ('EMP1668', 'MOSAB MOHAMMED ABBAS HADDAD', 'Pharmacist'::public.staff_role, true),
  ('EMP1670', 'HANAN AL DALI', 'Salesperson'::public.staff_role, true),
  ('EMP1672', 'ESRAA LOTFY SAAD ABDELLATIF MOHARM', 'Pharmacist'::public.staff_role, true),
  ('EMP1674', 'ESLAM HESHAM ELSAYED MOKHTAR GABALLAH', 'Pharmacist'::public.staff_role, true),
  ('EMP1676', 'MARWA MOHAMED OMAR MOHAMED', 'Pharmacist'::public.staff_role, true),
  ('EMP1677', 'RISLA CHITARRAYIL', 'Pharmacist'::public.staff_role, true),
  ('EMP1679', 'GRACIELLE DE BORJA VITOR', 'Salesperson'::public.staff_role, true),
  ('EMP1706', 'MOHAMED HAMED ELHUSSEINI ELTANTAWI', 'Pharmacist'::public.staff_role, true),
  ('EMP1715', 'SURESH NAGARAJAN', 'Pharmacist'::public.staff_role, true),
  ('EMP1716', 'AHMED MOHAMED TAREK MOHAMED MAMDOUH MAHMOUD', 'Pharmacist'::public.staff_role, true),
  ('EMP1733', 'MOSTAFA MABROUK SALOUMA MOHAMED', 'Salesperson'::public.staff_role, true),
  ('EMP1734', 'EMAN AHMED ELSHHAT ELNGAR', 'Salesperson'::public.staff_role, true),
  ('EMP1740', 'MUHAMMAD ELSAYED BEDEIR MUHAMMAD ELKHOLEY', 'Salesperson'::public.staff_role, true),
  ('EMP1742', 'ISLAM ABDELMAWLA ELSAYED ABDELMAWLA', 'Pharmacist'::public.staff_role, true),
  ('EMP1743', 'AHMED SALAH ABDELNABY ELHENNAWI', 'Pharmacist'::public.staff_role, true),
  ('EMP1744', 'EZZAT ABED ABDELHAMED ABDELWAHAB ABDELHAFEZ', 'Pharmacist'::public.staff_role, true),
  ('EMP1745', 'HAZEM MOHAMED SAAD ABDELWAHAB', 'Pharmacist'::public.staff_role, true),
  ('EMP1746', 'SAMI TAHA ABDELAATI TAHA SEWILAM', 'Pharmacist'::public.staff_role, true),
  ('EMP1749', 'ISLAM ALI WAHDAN AYOUB ELSHERBINI', 'Pharmacist'::public.staff_role, true),
  ('EMP1750', 'ZIA UR REHMAN', 'Pharmacist'::public.staff_role, true),
  ('EMP1751', 'ABDUL SAMAD UMER FAROOQ', 'Pharmacist'::public.staff_role, true),
  ('EMP1753', 'NOURHAN ABDELNASSER ELSAYED ELSHERBINI', 'Pharmacist'::public.staff_role, true),
  ('EMP1756', 'TAREK SAAD ABDELMOAMEN ALI', 'Pharmacist'::public.staff_role, true),
  ('EMP1759', 'AHMED KAMAL IBRAHIM ALI SOLIMAN', 'Pharmacist'::public.staff_role, true),
  ('EMP1766', 'ABANOUB BOULES SABRY DERIAS', 'Pharmacist'::public.staff_role, true),
  ('EMP1769', 'MOHAMED RAMZY ELKOTB ABDELHAMID', 'Pharmacist'::public.staff_role, true),
  ('EMP1770', 'JOHN SOLIMAN RAMZY BEKHET FALFAL', 'Pharmacist'::public.staff_role, true),
  ('EMP1773', 'REFAAT ABDELAZIZ AWAD ELDESOKY', 'Salesperson'::public.staff_role, true),
  ('EMP1775', 'AHMED ELSAYED AHMED MOHAMED ELGELANY', 'Pharmacist'::public.staff_role, true),
  ('EMP1776', 'RONALYNN LORENZO MATIC', 'Salesperson'::public.staff_role, true),
  ('EMP1778', 'HUSSEIN GHANEM MAKAWI ABDELKAWI', 'Salesperson'::public.staff_role, true),
  ('EMP1794', 'AIRAH EBERLEEN PERICO', 'Salesperson'::public.staff_role, true),
  ('EMP1803', 'HASAN ELSAID HASAN ABDELAZIZ', 'Salesperson'::public.staff_role, true),
  ('EMP1806', 'MAHMOUD SOBHI MOHAMED MOHAMED ELDOMYATY', 'Pharmacist'::public.staff_role, true),
  ('EMP1809', 'JONNALYN PADILLA PEREZ', 'Salesperson'::public.staff_role, true),
  ('EMP1811', 'AHMED SALAHELDIN AHMED GHALY', 'Pharmacist'::public.staff_role, true),
  ('EMP1822', 'MOSTAFA MAHMOUD MOHAMED ELSREOGY', 'Salesperson'::public.staff_role, true),
  ('EMP1840', 'MOHAMMED MOSTAFA MOHAMMED ELSHENNAWY', 'Pharmacist'::public.staff_role, true),
  ('EMP1841', 'ZENDIE MAE SALARDA VELONERO', 'Salesperson'::public.staff_role, true),
  ('EMP1850', 'GAMAL ABDELNASER ABDELHAMID AHMED ABDELRAHMAN', 'Pharmacist'::public.staff_role, true),
  ('EMP1851', 'AHMED MOHAMED SAAD MOHAMED MAHMOUD ELATFY', 'Pharmacist'::public.staff_role, true),
  ('EMP1863', 'SOHA ABDELHAMID BAYOUMI OKDA', 'Pharmacist'::public.staff_role, true),
  ('EMP1875', 'SAIF RAIF WASSFY HANNA', 'Pharmacist'::public.staff_role, true),
  ('EMP1876', 'ABDELRAHMAN MAHMOUD FAWZY MAHMOUD', 'Pharmacist'::public.staff_role, true),
  ('EMP1879', 'ZUBAIR POTTACHOLA', 'Pharmacist'::public.staff_role, true),
  ('EMP1880', 'AHMED MOSILHY ABDELALEEM MOSILHY', 'Pharmacist'::public.staff_role, true),
  ('EMP1890', 'SAIF MOHAMED MOHAMED GAD ELASSAL', 'Pharmacist'::public.staff_role, true),
  ('EMP1902', 'ALAA MORSY MOHAMMAD BARAKAT', 'Pharmacist'::public.staff_role, true),
  ('EMP1903', 'SHADI MOHAMED MAHMOUD WAHBA BEHIR', 'Pharmacist'::public.staff_role, true),
  ('EMP1907', 'ALENOUD MOUSTAFA KAMEL ABDELGHAFAR', 'Salesperson'::public.staff_role, true),
  ('EMP1914', 'ABDERAHMAN MOSTAFA MOHAMED ELSAYED SOLIMAN', 'Pharmacist'::public.staff_role, true)
ON CONFLICT (staff_code) DO NOTHING;
