-- Simplified branch seed — just the names.
-- emirate and branch_profile are placeholders; update from the app after creation.
INSERT INTO public.branches (name, emirate, branch_profile, active)
VALUES
  ('Al Ain',            'Dubai',  'Retail'::public.branch_profile, true),
  ('Al Quoz',           'Dubai',  'Retail'::public.branch_profile, true),
  ('Arjan',             'Dubai',  'Retail'::public.branch_profile, true),
  ('Atlantis 1',        'Dubai',  'Retail'::public.branch_profile, true),
  ('Atlantis 2',        'Dubai',  'Retail'::public.branch_profile, true),
  ('Business Bay',      'Dubai',  'Retail'::public.branch_profile, true),
  ('Capital',           'Dubai',  'Retail'::public.branch_profile, true),
  ('Center',            'Dubai',  'Retail'::public.branch_profile, true),
  ('Circle',            'Dubai',  'Retail'::public.branch_profile, true),
  ('City Walk',         'Dubai',  'Retail'::public.branch_profile, true),
  ('Corniche',          'Dubai',  'Retail'::public.branch_profile, true),
  ('DCC',               'Dubai',  'Retail'::public.branch_profile, true),
  ('DHCC',              'Dubai',  'Retail'::public.branch_profile, true),
  ('GM 1',              'Dubai',  'Retail'::public.branch_profile, true),
  ('GM 2',              'Dubai',  'Retail'::public.branch_profile, true),
  ('Gate Avenue',       'Dubai',  'Retail'::public.branch_profile, true),
  ('Greens',            'Dubai',  'Retail'::public.branch_profile, true),
  ('Jumeirah',          'Dubai',  'Retail'::public.branch_profile, true),
  ('Madinat Al Riyad',  'Dubai',  'Retail'::public.branch_profile, true),
  ('Mirdif',            'Dubai',  'Retail'::public.branch_profile, true),
  ('Nad Al Shiba',      'Dubai',  'Retail'::public.branch_profile, true),
  ('Old Town',          'Dubai',  'Retail'::public.branch_profile, true),
  ('One Central',       'Dubai',  'Retail'::public.branch_profile, true),
  ('Palm',              'Dubai',  'Retail'::public.branch_profile, true),
  ('Park',              'Dubai',  'Retail'::public.branch_profile, true),
  ('Promenade',         'Dubai',  'Retail'::public.branch_profile, true),
  ('RAK',               'Dubai',  'Retail'::public.branch_profile, true),
  ('Shamkha',           'Dubai',  'Retail'::public.branch_profile, true),
  ('Sharjah',           'Dubai',  'Retail'::public.branch_profile, true),
  ('South',             'Dubai',  'Retail'::public.branch_profile, true),
  ('Star',              'Dubai',  'Retail'::public.branch_profile, true),
  ('Studio City',       'Dubai',  'Retail'::public.branch_profile, true),
  ('Zahia',             'Dubai',  'Retail'::public.branch_profile, true)
ON CONFLICT (name) DO NOTHING;
