/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssignAdminRouteImport } from './routes/assign-admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedVisitsNewRouteImport } from './routes/_authenticated/visits/new'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff/$staffId'
import { Route as AuthenticatedBranchesBranchIdRouteImport } from './routes/_authenticated/branches/$branchId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminChecklistRouteImport } from './routes/_authenticated/admin/checklist'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedVisitsVisitIdIndexRouteImport } from './routes/_authenticated/visits/$visitId/index'
import { Route as AuthenticatedVisitsVisitIdReportRouteImport } from './routes/_authenticated/visits/$visitId/report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignAdminRoute = AssignAdminRouteImport.update({
  id: '/assign-admin',
  path: '/assign-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitsNewRoute = AuthenticatedVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesBranchIdRoute =
  AuthenticatedBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminChecklistRoute =
  AuthenticatedAdminChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedVisitsVisitIdIndexRoute =
  AuthenticatedVisitsVisitIdIndexRouteImport.update({
    id: '/visits/$visitId/',
    path: '/visits/$visitId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitsVisitIdReportRoute =
  AuthenticatedVisitsVisitIdReportRouteImport.update({
    id: '/visits/$visitId/report',
    path: '/visits/$visitId/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assign-admin': typeof AssignAdminRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
  '/visits/$visitId/': typeof AuthenticatedVisitsVisitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assign-admin': typeof AssignAdminRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assign-admin': typeof AssignAdminRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/visits/new': typeof AuthenticatedVisitsNewRoute
  '/_authenticated/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
  '/_authenticated/visits/$visitId/': typeof AuthenticatedVisitsVisitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assign-admin'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/branches'
    | '/admin/checklist'
    | '/admin/staff'
    | '/admin/users'
    | '/branches/$branchId'
    | '/staff/$staffId'
    | '/visits/new'
    | '/visits/$visitId/report'
    | '/visits/$visitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assign-admin'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/branches'
    | '/admin/checklist'
    | '/admin/staff'
    | '/admin/users'
    | '/branches/$branchId'
    | '/staff/$staffId'
    | '/visits/new'
    | '/visits/$visitId/report'
    | '/visits/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assign-admin'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/checklist'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/users'
    | '/_authenticated/branches/$branchId'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/visits/new'
    | '/_authenticated/visits/$visitId/report'
    | '/_authenticated/visits/$visitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssignAdminRoute: typeof AssignAdminRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assign-admin': {
      id: '/assign-admin'
      path: '/assign-admin'
      fullPath: '/assign-admin'
      preLoaderRoute: typeof AssignAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/new': {
      id: '/_authenticated/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof AuthenticatedVisitsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/$branchId': {
      id: '/_authenticated/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof AuthenticatedBranchesBranchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/checklist': {
      id: '/_authenticated/admin/checklist'
      path: '/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof AuthenticatedAdminChecklistRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/visits/$visitId/': {
      id: '/_authenticated/visits/$visitId/'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId/'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits/$visitId/report': {
      id: '/_authenticated/visits/$visitId/report'
      path: '/visits/$visitId/report'
      fullPath: '/visits/$visitId/report'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminChecklistRoute: typeof AuthenticatedAdminChecklistRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
    AuthenticatedAdminChecklistRoute: AuthenticatedAdminChecklistRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedBranchesBranchIdRoute: typeof AuthenticatedBranchesBranchIdRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
  AuthenticatedVisitsNewRoute: typeof AuthenticatedVisitsNewRoute
  AuthenticatedVisitsVisitIdReportRoute: typeof AuthenticatedVisitsVisitIdReportRoute
  AuthenticatedVisitsVisitIdIndexRoute: typeof AuthenticatedVisitsVisitIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedBranchesBranchIdRoute: AuthenticatedBranchesBranchIdRoute,
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
  AuthenticatedVisitsNewRoute: AuthenticatedVisitsNewRoute,
  AuthenticatedVisitsVisitIdReportRoute: AuthenticatedVisitsVisitIdReportRoute,
  AuthenticatedVisitsVisitIdIndexRoute: AuthenticatedVisitsVisitIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssignAdminRoute: AssignAdminRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
