/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedVisitsNewRouteImport } from './routes/_authenticated/visits/new'
import { Route as AuthenticatedBranchesBranchIdRouteImport } from './routes/_authenticated/branches/$branchId'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff/$staffId'
import { Route as AuthenticatedVisitsVisitIdIndexRouteImport } from './routes/_authenticated/visits/$visitId/index'
import { Route as AuthenticatedVisitsVisitIdReportRouteImport } from './routes/_authenticated/visits/$visitId/report'
import { Route as AuthenticatedAdminChecklistRouteImport } from './routes/_authenticated/admin/checklist'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsNewRoute = AuthenticatedVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchesBranchIdRoute = AuthenticatedBranchesBranchIdRouteImport.update({
  id: '/branches/$branchId',
  path: '/branches/$branchId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffStaffIdRoute = AuthenticatedStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsVisitIdIndexRoute = AuthenticatedVisitsVisitIdIndexRouteImport.update({
  id: '/visits/$visitId/',
  path: '/visits/$visitId/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsVisitIdReportRoute = AuthenticatedVisitsVisitIdReportRouteImport.update({
  id: '/visits/$visitId/report',
  path: '/visits/$visitId/report',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminChecklistRoute = AuthenticatedAdminChecklistRouteImport.update({
  id: '/admin/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBranchesRoute = AuthenticatedAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdIndexRoute
  '/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdIndexRoute
  '/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/checklist': typeof AuthenticatedAdminChecklistRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/visits/new': typeof AuthenticatedVisitsNewRoute
  '/_authenticated/branches/$branchId': typeof AuthenticatedBranchesBranchIdRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/_authenticated/visits/$visitId/': typeof AuthenticatedVisitsVisitIdIndexRoute
  '/_authenticated/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminChecklistRoute: typeof AuthenticatedAdminChecklistRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
}
const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminChecklistRoute,
  AuthenticatedAdminUsersRoute,
  AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminStaffRoute,
}
const AuthenticatedAdminRouteWithChildren = AuthenticatedAdminRoute._addFileChildren(
  AuthenticatedAdminRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedVisitsNewRoute: typeof AuthenticatedVisitsNewRoute
  AuthenticatedBranchesBranchIdRoute: typeof AuthenticatedBranchesBranchIdRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
  AuthenticatedVisitsVisitIdIndexRoute: typeof AuthenticatedVisitsVisitIdIndexRoute
  AuthenticatedVisitsVisitIdReportRoute: typeof AuthenticatedVisitsVisitIdReportRoute
}
const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedVisitsNewRoute,
  AuthenticatedBranchesBranchIdRoute,
  AuthenticatedStaffStaffIdRoute,
  AuthenticatedVisitsVisitIdIndexRoute,
  AuthenticatedVisitsVisitIdReportRoute,
}
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/checklist': {
      id: '/_authenticated/admin/checklist'
      path: '/admin/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof AuthenticatedAdminChecklistRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/visits/new': {
      id: '/_authenticated/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof AuthenticatedVisitsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches/$branchId': {
      id: '/_authenticated/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof AuthenticatedBranchesBranchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits/$visitId/': {
      id: '/_authenticated/visits/$visitId/'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits/$visitId/report': {
      id: '/_authenticated/visits/$visitId/report'
      path: '/visits/$visitId/report'
      fullPath: '/visits/$visitId/report'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
