/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVisitsNewRouteImport } from './routes/_authenticated/visits/new'
import { Route as AuthenticatedVisitsVisitIdIndexRouteImport } from './routes/_authenticated/visits/$visitId/index'
import { Route as AuthenticatedVisitsVisitIdReportRouteImport } from './routes/_authenticated/visits/$visitId/report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsNewRoute = AuthenticatedVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsVisitIdIndexRoute = AuthenticatedVisitsVisitIdIndexRouteImport.update({
  id: '/visits/$visitId/',
  path: '/visits/$visitId/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitsVisitIdReportRoute = AuthenticatedVisitsVisitIdReportRouteImport.update({
  id: '/visits/$visitId/report',
  path: '/visits/$visitId/report',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdIndexRoute
  '/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/visits/new': typeof AuthenticatedVisitsNewRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdIndexRoute
  '/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/visits/new': typeof AuthenticatedVisitsNewRoute
  '/_authenticated/visits/$visitId/': typeof AuthenticatedVisitsVisitIdIndexRoute
  '/_authenticated/visits/$visitId/report': typeof AuthenticatedVisitsVisitIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/visits/new'
    | '/visits/$visitId'
    | '/visits/$visitId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/visits/new'
    | '/visits/$visitId'
    | '/visits/$visitId/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/visits/new'
    | '/_authenticated/visits/$visitId/'
    | '/_authenticated/visits/$visitId/report'
  fileRoutesById: FileRoutesById
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVisitsNewRoute: typeof AuthenticatedVisitsNewRoute
  AuthenticatedVisitsVisitIdIndexRoute: typeof AuthenticatedVisitsVisitIdIndexRoute
  AuthenticatedVisitsVisitIdReportRoute: typeof AuthenticatedVisitsVisitIdReportRoute
}
const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVisitsNewRoute: AuthenticatedVisitsNewRoute,
  AuthenticatedVisitsVisitIdIndexRoute: AuthenticatedVisitsVisitIdIndexRoute,
  AuthenticatedVisitsVisitIdReportRoute: AuthenticatedVisitsVisitIdReportRoute,
}
const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits/new': {
      id: '/_authenticated/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof AuthenticatedVisitsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits/$visitId/': {
      id: '/_authenticated/visits/$visitId/'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits/$visitId/report': {
      id: '/_authenticated/visits/$visitId/report'
      path: '/visits/$visitId/report'
      fullPath: '/visits/$visitId/report'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
