-- Staff seed generated from payroll CSV
-- Run this AFTER branches are seeded (the branches seed is idempotent)

-- Generated: /Users/mohammedalsheraey/Desktop/June-2026_Payroll_Table_01-07-2026.csv

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM public.staff WHERE staff_code LIKE 'EMP%' LIMIT 1) THEN RETURN; END IF;
END $$;

WITH
  al_ain AS (SELECT id FROM public.branches WHERE name = 'Al Ain' LIMIT 1),
  al_quoz AS (SELECT id FROM public.branches WHERE name = 'Al Quoz' LIMIT 1),
  arjan AS (SELECT id FROM public.branches WHERE name = 'Arjan' LIMIT 1),
  atlantis_1 AS (SELECT id FROM public.branches WHERE name = 'Atlantis 1' LIMIT 1),
  atlantis_2 AS (SELECT id FROM public.branches WHERE name = 'Atlantis 2' LIMIT 1),
  business_bay AS (SELECT id FROM public.branches WHERE name = 'Business Bay' LIMIT 1),
  capital AS (SELECT id FROM public.branches WHERE name = 'Capital' LIMIT 1),
  center AS (SELECT id FROM public.branches WHERE name = 'Center' LIMIT 1),
  circle AS (SELECT id FROM public.branches WHERE name = 'Circle' LIMIT 1),
  city_walk AS (SELECT id FROM public.branches WHERE name = 'City Walk' LIMIT 1),
  corniche AS (SELECT id FROM public.branches WHERE name = 'Corniche' LIMIT 1),
  dcc AS (SELECT id FROM public.branches WHERE name = 'DCC' LIMIT 1),
  dhcc AS (SELECT id FROM public.branches WHERE name = 'DHCC' LIMIT 1),
  gm_1 AS (SELECT id FROM public.branches WHERE name = 'GM 1' LIMIT 1),
  gm_2 AS (SELECT id FROM public.branches WHERE name = 'GM 2' LIMIT 1),
  gate_avenue AS (SELECT id FROM public.branches WHERE name = 'Gate Avenue' LIMIT 1),
  greens AS (SELECT id FROM public.branches WHERE name = 'Greens' LIMIT 1),
  jumeirah AS (SELECT id FROM public.branches WHERE name = 'Jumeirah' LIMIT 1),
  madinat_al_riyad AS (SELECT id FROM public.branches WHERE name = 'Madinat Al Riyad' LIMIT 1),
  mirdif AS (SELECT id FROM public.branches WHERE name = 'Mirdif' LIMIT 1),
  nad_al_shiba AS (SELECT id FROM public.branches WHERE name = 'Nad Al Shiba' LIMIT 1),
  old_town AS (SELECT id FROM public.branches WHERE name = 'Old Town' LIMIT 1),
  one_central AS (SELECT id FROM public.branches WHERE name = 'One Central' LIMIT 1),
  palm AS (SELECT id FROM public.branches WHERE name = 'Palm' LIMIT 1),
  park AS (SELECT id FROM public.branches WHERE name = 'Park' LIMIT 1),
  promenade AS (SELECT id FROM public.branches WHERE name = 'Promenade' LIMIT 1),
  rak AS (SELECT id FROM public.branches WHERE name = 'RAK' LIMIT 1),
  shamkha AS (SELECT id FROM public.branches WHERE name = 'Shamkha' LIMIT 1),
  sharjah AS (SELECT id FROM public.branches WHERE name = 'Sharjah' LIMIT 1),
  south AS (SELECT id FROM public.branches WHERE name = 'South' LIMIT 1),
  star AS (SELECT id FROM public.branches WHERE name = 'Star' LIMIT 1),
  studio_city AS (SELECT id FROM public.branches WHERE name = 'Studio City' LIMIT 1),
  zahia AS (SELECT id FROM public.branches WHERE name = 'Zahia' LIMIT 1)
INSERT INTO public.staff (staff_code, full_name, role, branch_id, dha_license_status, active)
SELECT * FROM (VALUES
  ('EMP0021', 'MAGDI IBRAHIM ELTOHAMI MOHAMED BADI', 'Salesperson', (SELECT id FROM al_quoz), NULL, true),
  ('EMP0029', 'MELANI BELTRAN LISING', 'Salesperson', (SELECT id FROM al_quoz), NULL, true),
  ('EMP0167', 'FIAZ AKHTAR  QASMI', 'Pharmacist', (SELECT id FROM palm), 'Active', true),
  ('EMP0191', 'MOHAMED ABOUELOYON SALAH MOHAMED AYOUB', 'Salesperson', (SELECT id FROM atlantis_2), NULL, true),
  ('EMP0222', 'LUBNA  TABASUM', 'Branch Manager', (SELECT id FROM capital), NULL, true),
  ('EMP0359', 'ALI MUKTHAR ABDUL SALEEM', 'Pharmacist', (SELECT id FROM park), 'Active', true),
  ('EMP0375', 'HOSSAM MOHAMED KAMEL AHMED', 'Salesperson', (SELECT id FROM atlantis_1), NULL, true),
  ('EMP0387', 'MALEK AHMED OMAR AHMED DARWISH', 'Salesperson', (SELECT id FROM capital), NULL, true),
  ('EMP0424', 'HARLENE PATAYAN', 'Pharmacist', (SELECT id FROM dhcc), 'Active', true),
  ('EMP0441', 'JANE DE GUZMAN SOLIMAN', 'Branch Manager', (SELECT id FROM park), NULL, true),
  ('EMP0448', 'WAEL MAHROUS AYOUB AHMED', 'Salesperson', (SELECT id FROM city_walk), NULL, true),
  ('EMP0474', 'JENNIFER GARCIA', 'Salesperson', (SELECT id FROM arjan), NULL, true),
  ('EMP0500', 'RAMADAN ABOUZEID RAMADAN ALI', 'Pharmacist', (SELECT id FROM atlantis_2), 'Active', true),
  ('EMP0585', 'JOJIT COTELO MENDOZA', 'Salesperson', (SELECT id FROM park), NULL, true),
  ('EMP0611', 'MOHAMED KAMAL ABBAS IBRAHIM LEILA', 'Salesperson', (SELECT id FROM al_ain), NULL, true),
  ('EMP0612', 'KARIM MANSOUR SALEH LISI', 'Salesperson', (SELECT id FROM al_quoz), NULL, true),
  ('EMP0618', 'YAHIA MAHMOUD MEGAHED BADWI', 'Salesperson', (SELECT id FROM corniche), NULL, true),
  ('EMP0622', 'KARIM ABDELLATIF ELSAYED ABDELLATIF', 'Salesperson', (SELECT id FROM nad_al_shiba), NULL, true),
  ('EMP0636', 'QURAT UL AIN', 'Pharmacist', (SELECT id FROM city_walk), 'Active', true),
  ('EMP0660', 'MOHAMED ADEL ABDELALIM ELHANAFI ELROZY', 'Pharmacist', (SELECT id FROM mirdif), 'Active', true),
  ('EMP0677', 'PRINCESS SARAH BAYANI', 'Pharmacist', (SELECT id FROM palm), 'Active', true),
  ('EMP0678', 'SARAH MOUSTAFA ABDELRAHMAN MOUSTAFA', 'Pharmacist', (SELECT id FROM circle), 'Active', true),
  ('EMP0692', 'MOHAMED ABDELZAHER NOUR AHMED', 'Salesperson', (SELECT id FROM dhcc), NULL, true),
  ('EMP0693', 'AHMED MOHAMED ATTIA ISMAIL BADAWI', 'Salesperson', (SELECT id FROM corniche), NULL, true),
  ('EMP0830', 'IMRAN MAHMOOD', 'Salesperson', (SELECT id FROM arjan), NULL, true),
  ('EMP0864', 'ROSHELLE SUSTENTO', 'Pharmacist', (SELECT id FROM city_walk), 'Active', true),
  ('EMP0890', 'SHAMEER NADUVILA VALAPPIL', 'Pharmacist', (SELECT id FROM dhcc), 'Active', true),
  ('EMP0896', 'IMRAN KHAN', 'Salesperson', (SELECT id FROM park), NULL, true),
  ('EMP0937', 'RAMY AHMED MOHAMED HAMZAWY HARBY', 'Salesperson', (SELECT id FROM dhcc), NULL, true),
  ('EMP0959', 'DARYLL CABILIN EUGENIO', 'Salesperson', (SELECT id FROM studio_city), NULL, true),
  ('EMP0963', 'TAMER IBRAHIM MABROUK AYOUB', 'Pharmacist', (SELECT id FROM park), 'Active', true),
  ('EMP0998', 'MD MAZHARUL ISLAM', 'Branch Manager', (SELECT id FROM circle), NULL, true),
  ('EMP1003', 'BILAL MUHAMMAD RIAZ', 'Salesperson', (SELECT id FROM arjan), NULL, true),
  ('EMP1018', 'KAREEM MOHAMED SALAH GODA ELSAYED', 'Branch Manager', (SELECT id FROM al_quoz), NULL, true),
  ('EMP1019', 'GAMAL SAYED ABDELMAWGOUD AHMED', 'Salesperson', (SELECT id FROM arjan), NULL, true),
  ('EMP1025', 'MOHAMED REDA SABER FATHALLA FATHALLA', 'Salesperson', (SELECT id FROM corniche), NULL, true),
  ('EMP1050', 'RIZALINA MADAYAG', 'Pharmacist', (SELECT id FROM studio_city), 'Active', true),
  ('EMP1062', 'ABDELRAHMAN ELEMAM ABDELHAY SHERA', 'Pharmacist', (SELECT id FROM old_town), 'Active', true),
  ('EMP1083', 'MOHAMED METWALLY ELGERIDY', 'Salesperson', (SELECT id FROM nad_al_shiba), NULL, true),
  ('EMP1113', 'ABBAS BANDE HASSAN', 'Pharmacist', (SELECT id FROM mirdif), 'Active', true),
  ('EMP1143', 'YOUSRI MOHAMED FATHY GAD', 'Salesperson', (SELECT id FROM capital), NULL, true),
  ('EMP1187', 'ALLEN MAE SANDRO', 'Pharmacist', (SELECT id FROM atlantis_1), 'Active', true),
  ('EMP1188', 'ZEESHAN RAZZAQ', 'Pharmacist', (SELECT id FROM zahia), 'Active', true),
  ('EMP1189', 'MOHAMED ELSAYED ELSHESHTAWI ELSEBAEI', 'Salesperson', (SELECT id FROM promenade), NULL, true),
  ('EMP1229', 'AHMED MAHER MAAMOUN MAHMOUD SALMA', 'Salesperson', (SELECT id FROM gm_2), NULL, true),
  ('EMP1289', 'VIANNE GIA GUMABAO MACUTAY', 'Pharmacist', (SELECT id FROM gate_avenue), 'Active', true),
  ('EMP1290', 'NOSIBA MOHAMED SIDDIG', 'Pharmacist', (SELECT id FROM rak), 'Active', true),
  ('EMP1292', 'MOHAMED GAMAL ABDELMAGUID ELSADANY', 'Pharmacist', (SELECT id FROM circle), 'Active', true),
  ('EMP1296', 'MARWA HUSSIN MOHAMED ALASS', 'Pharmacist', (SELECT id FROM nad_al_shiba), 'Active', true),
  ('EMP1299', 'OLA MOHAMMED ABUZAID ALI', 'Pharmacist', (SELECT id FROM nad_al_shiba), 'Active', true),
  ('EMP1312', 'GERLIE ROSE FELICIANO SARTE', 'Pharmacist', (SELECT id FROM promenade), 'Active', true),
  ('EMP1316', 'AHMED OTHMAN GHANEM OTHMAN', 'Salesperson', (SELECT id FROM gm_2), NULL, true),
  ('EMP1326', 'REDA MOHAMED ABOELFTOH ELSHERIF', 'Pharmacist', (SELECT id FROM palm), 'Active', true),
  ('EMP1331', 'JOYCE DELMUNDO', 'Pharmacist', (SELECT id FROM dcc), 'Active', true),
  ('EMP1332', 'MA JOYCE ANN SERRANO', 'Pharmacist', (SELECT id FROM star), 'Active', true),
  ('EMP1342', 'ABDELRAHMAN HASSAN FATHY HASSAN', 'Salesperson', (SELECT id FROM capital), NULL, true),
  ('EMP1346', 'MOUSTAFA ALI MOHAMED MARAWAN GAD', 'Salesperson', (SELECT id FROM al_ain), NULL, true),
  ('EMP1350', 'MOHAMAD NIDAL BADER ALDEEN ALMOUSLI', 'Pharmacist', (SELECT id FROM al_ain), 'Active', true),
  ('EMP1369', 'MOHAMED SABRY ZAKARIA MOHAMED KEWAN', 'Salesperson', (SELECT id FROM dhcc), NULL, true),
  ('EMP1425', 'HAITHAM ALDURRA', 'Branch Manager', (SELECT id FROM zahia), NULL, true),
  ('EMP1442', 'KHALED MOHAMED MOHAMED ELSAID ABDELAZIZ TAKSIRA', 'Salesperson', (SELECT id FROM zahia), NULL, true),
  ('EMP1445', 'NEVINE SERAGELDIN HUSSIEN KADRY', 'Pharmacist', (SELECT id FROM old_town), 'Active', true),
  ('EMP1446', 'AHMED MOUSTAFA MOHAMED MOUSTAFA KOTB', 'Pharmacist', (SELECT id FROM south), 'Active', true),
  ('EMP1449', 'MAHMOUD ABDULKADER ANIS KARKANAWI', 'Pharmacist', (SELECT id FROM sharjah), 'Active', true),
  ('EMP1459', 'OMNIA AHMED ATTIA MOHAMED IBRAHIM', 'Pharmacist', (SELECT id FROM city_walk), 'Active', true),
  ('EMP1478', 'SHAYMAA IBRAHIM ABDELMAGED IBRAHIM', 'Salesperson', (SELECT id FROM circle), NULL, true),
  ('EMP1482', 'FATMA MAGDY SALAMA ABUSREA', 'Pharmacist', (SELECT id FROM center), 'Active', true),
  ('EMP1483', 'RASHIDA ERANHIKKAL', 'Pharmacist', (SELECT id FROM madinat_al_riyad), 'Active', true),
  ('EMP1489', 'ABDELMONEIM ABDELAZIM ABDELMONEIM MAHMOUD SOLIMAN', 'Pharmacist', (SELECT id FROM nad_al_shiba), 'Active', true),
  ('EMP1490', 'JOAN MAE GARCIA GARCIA', 'Pharmacist', (SELECT id FROM promenade), 'Active', true),
  ('EMP1502', 'FIRDOUS UDDIN AMER MOHAMMED', 'Pharmacist', (SELECT id FROM dhcc), 'Active', true),
  ('EMP1520', 'SAEED JASEEM MULLASSERI', 'Pharmacist', (SELECT id FROM shamkha), 'Active', true),
  ('EMP1521', 'VANESSA HERMOGENO AGAPITO', 'Pharmacist', (SELECT id FROM arjan), 'Active', true),
  ('EMP1649', 'MOHAMED TAHA ELGABRI IBRAHIM ELHENNAWI', 'Salesperson', (SELECT id FROM park), NULL, true),
  ('EMP1651', 'NOURELHODA ESSMAT MOATAMED SAYED', 'Branch Manager', (SELECT id FROM corniche), NULL, true),
  ('EMP1652', 'AMR MOHAMED ALAA MOHAMED IBRAHIM ALDOKLA', 'Pharmacist', (SELECT id FROM one_central), 'Active', true),
  ('EMP1657', 'SANJID CHIRAKKAL', 'Pharmacist', (SELECT id FROM al_ain), 'Active', true),
  ('EMP1660', 'MOHAMED HASSAN NASR GHANNAM', 'Pharmacist', (SELECT id FROM arjan), 'Active', true),
  ('EMP1662', 'AHMED MOHAMED MAHMOUD MOHAMED', 'Pharmacist', (SELECT id FROM dhcc), 'Active', true),
  ('EMP1663', 'REMYLYN DEALAGDON TOLORIO', 'Salesperson', (SELECT id FROM park), NULL, true),
  ('EMP1664', 'MARIEL RIZARO ELMENZO', 'Salesperson', (SELECT id FROM studio_city), NULL, true),
  ('EMP1665', 'ABDELAZIZ FAROUK SHAMESELDIN ELHOGRY', 'Salesperson', (SELECT id FROM business_bay), NULL, true),
  ('EMP1667', 'MOHAMED MONIR ABDELMONEM IBRAHIM GHAZAL', 'Salesperson', (SELECT id FROM park), NULL, true),
  ('EMP1668', 'MOSAB MOHAMMED ABBAS HADDAD', 'Pharmacist', (SELECT id FROM jumeirah), 'Active', true),
  ('EMP1670', 'HANAN AL DALI', 'Salesperson', (SELECT id FROM mirdif), NULL, true),
  ('EMP1672', 'ESRAA LOTFY SAAD ABDELLATIF MOHARM', 'Pharmacist', (SELECT id FROM gm_1), 'Active', true),
  ('EMP1674', 'ESLAM HESHAM ELSAYED MOKHTAR GABALLAH', 'Pharmacist', (SELECT id FROM corniche), 'Active', true),
  ('EMP1676', 'MARWA MOHAMED OMAR MOHAMED', 'Pharmacist', (SELECT id FROM greens), 'Active', true),
  ('EMP1677', 'RISLA CHITARRAYIL', 'Pharmacist', (SELECT id FROM corniche), 'Active', true),
  ('EMP1679', 'GRACIELLE DE BORJA VITOR', 'Salesperson', (SELECT id FROM city_walk), NULL, true),
  ('EMP1706', 'MOHAMED HAMED ELHUSSEINI ELTANTAWI', 'Pharmacist', (SELECT id FROM studio_city), 'Active', true),
  ('EMP1715', 'SURESH NAGARAJAN', 'Pharmacist', (SELECT id FROM mirdif), 'Active', true),
  ('EMP1716', 'AHMED MOHAMED TAREK MOHAMED MAMDOUH MAHMOUD', 'Pharmacist', (SELECT id FROM mirdif), 'Active', true),
  ('EMP1733', 'MOSTAFA MABROUK SALOUMA MOHAMED', 'Salesperson', (SELECT id FROM business_bay), NULL, true),
  ('EMP1734', 'EMAN AHMED ELSHHAT ELNGAR', 'Salesperson', (SELECT id FROM gm_2), NULL, true),
  ('EMP1740', 'MUHAMMAD ELSAYED BEDEIR MUHAMMAD ELKHOLEY', 'Salesperson', (SELECT id FROM madinat_al_riyad), NULL, true),
  ('EMP1742', 'ISLAM ABDELMAWLA ELSAYED ABDELMAWLA', 'Pharmacist', (SELECT id FROM dhcc), 'Active', true),
  ('EMP1743', 'AHMED SALAH ABDELNABY ELHENNAWI', 'Pharmacist', (SELECT id FROM center), 'Active', true),
  ('EMP1744', 'EZZAT ABED ABDELHAMED ABDELWAHAB ABDELHAFEZ', 'Pharmacist', (SELECT id FROM city_walk), 'Active', true),
  ('EMP1745', 'HAZEM MOHAMED SAAD ABDELWAHAB', 'Pharmacist', (SELECT id FROM gm_2), 'Active', true),
  ('EMP1746', 'SAMI TAHA ABDELAATI TAHA SEWILAM', 'Pharmacist', (SELECT id FROM one_central), 'Active', true),
  ('EMP1749', 'ISLAM ALI WAHDAN AYOUB ELSHERBINI', 'Pharmacist', (SELECT id FROM park), 'Active', true),
  ('EMP1750', 'ZIA UR REHMAN', 'Pharmacist', (SELECT id FROM zahia), 'Active', true),
  ('EMP1751', 'ABDUL SAMAD UMER FAROOQ', 'Pharmacist', (SELECT id FROM rak), 'Active', true),
  ('EMP1753', 'NOURHAN ABDELNASSER ELSAYED ELSHERBINI', 'Pharmacist', (SELECT id FROM south), 'Active', true),
  ('EMP1756', 'TAREK SAAD ABDELMOAMEN ALI', 'Pharmacist', (SELECT id FROM greens), 'Active', true),
  ('EMP1759', 'AHMED KAMAL IBRAHIM ALI SOLIMAN', 'Pharmacist', (SELECT id FROM circle), 'Active', true),
  ('EMP1766', 'ABANOUB BOULES SABRY DERIAS', 'Pharmacist', (SELECT id FROM park), 'Active', true),
  ('EMP1769', 'MOHAMED RAMZY ELKOTB ABDELHAMID', 'Pharmacist', (SELECT id FROM gm_1), 'Active', true),
  ('EMP1770', 'JOHN SOLIMAN RAMZY BEKHET FALFAL', 'Pharmacist', (SELECT id FROM center), 'Active', true),
  ('EMP1773', 'REFAAT ABDELAZIZ AWAD ELDESOKY', 'Salesperson', (SELECT id FROM promenade), NULL, true),
  ('EMP1775', 'AHMED ELSAYED AHMED MOHAMED ELGELANY', 'Pharmacist', (SELECT id FROM studio_city), 'Active', true),
  ('EMP1776', 'RONALYNN LORENZO MATIC', 'Salesperson', (SELECT id FROM dhcc), NULL, true),
  ('EMP1778', 'HUSSEIN GHANEM MAKAWI ABDELKAWI', 'Salesperson', (SELECT id FROM gm_2), NULL, true),
  ('EMP1794', 'AIRAH EBERLEEN PERICO', 'Salesperson', (SELECT id FROM dhcc), NULL, true),
  ('EMP1803', 'HASAN ELSAID HASAN ABDELAZIZ', 'Salesperson', (SELECT id FROM shamkha), NULL, true),
  ('EMP1806', 'MAHMOUD SOBHI MOHAMED MOHAMED ELDOMYATY', 'Pharmacist', (SELECT id FROM sharjah), 'Active', true),
  ('EMP1809', 'JONNALYN PADILLA PEREZ', 'Salesperson', (SELECT id FROM arjan), NULL, true),
  ('EMP1811', 'AHMED SALAHELDIN AHMED GHALY', 'Pharmacist', (SELECT id FROM arjan), 'Active', true),
  ('EMP1822', 'MOSTAFA MAHMOUD MOHAMED ELSREOGY', 'Salesperson', (SELECT id FROM al_quoz), NULL, true),
  ('EMP1840', 'MOHAMMED MOSTAFA MOHAMMED ELSHENNAWY', 'Pharmacist', (SELECT id FROM south), 'Active', true),
  ('EMP1841', 'ZENDIE MAE SALARDA VELONERO', 'Salesperson', (SELECT id FROM park), NULL, true),
  ('EMP1850', 'GAMAL ABDELNASER ABDELHAMID AHMED ABDELRAHMAN', 'Pharmacist', (SELECT id FROM business_bay), 'Active', true),
  ('EMP1851', 'AHMED MOHAMED SAAD MOHAMED MAHMOUD ELATFY', 'Pharmacist', (SELECT id FROM gm_2), 'Active', true),
  ('EMP1863', 'SOHA ABDELHAMID BAYOUMI OKDA', 'Pharmacist', (SELECT id FROM gm_1), 'Active', true),
  ('EMP1875', 'SAIF RAIF WASSFY HANNA', 'Pharmacist', (SELECT id FROM circle), 'Active', true),
  ('EMP1876', 'ABDELRAHMAN MAHMOUD FAWZY MAHMOUD', 'Pharmacist', (SELECT id FROM city_walk), 'Active', true),
  ('EMP1879', 'ZUBAIR POTTACHOLA', 'Pharmacist', (SELECT id FROM capital), 'Active', true),
  ('EMP1880', 'AHMED MOSILHY ABDELALEEM MOSILHY', 'Pharmacist', (SELECT id FROM al_ain), 'Active', true),
  ('EMP1890', 'SAIF MOHAMED MOHAMED GAD ELASSAL', 'Pharmacist', (SELECT id FROM business_bay), 'Active', true),
  ('EMP1902', 'ALAA MORSY MOHAMMAD BARAKAT', 'Pharmacist', (SELECT id FROM shamkha), 'Active', true),
  ('EMP1903', 'SHADI MOHAMED MAHMOUD WAHBA BEHIR', 'Pharmacist', (SELECT id FROM jumeirah), 'Active', true),
  ('EMP1907', 'ALENOUD MOUSTAFA KAMEL ABDELGHAFAR', 'Salesperson', (SELECT id FROM gm_2), NULL, true),
  ('EMP1914', 'ABDERAHMAN MOSTAFA MOHAMED ELSAYED SOLIMAN', 'Pharmacist', (SELECT id FROM palm), 'Active', true)
) AS t(staff_code, full_name, role, branch_id, dha_license_status, active)
ON CONFLICT (staff_code) DO NOTHING;

-- Total: 134 staff
